### ISSUE TITLE
Tow scrollbars

### ISSUE THREAD

**Issue by Julian-B90** [programmierbar/website#4]
Windows 10
Screen resolution 1366x768
Chrome  Version 96.0.4664.45 (Offizieller Build) (64-Bit)

![bug_programmier_bar](https://user-images.githubusercontent.com/4377396/144724750-f9ddd2a6-81ae-4ccc-892c-4a8ffa55210e.jpg)

**Comment by fabian-hiller** [comment]
Thank you very much for the tip. As soon as I have a Windows PC at hand in the evening, I will try to find a solution.

**Comment by fabian-hiller** [comment]
Hey @Julian-B90, what behavior of the website would you have expected at this point?

I checked the site yesterday and found that this is our expected behavior. We had already disabled background scrolling in the past with `overflow: hidden`, which then also removes the first scrollbar. However, showing and hiding the scrollbar makes the layout jump back and forth, so we decided against it.

I know it doesn't look pretty visually. However, it is necessary that the menu can also be used on smaller displays.
